apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py3ocp7ai-svc-development
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/py3ocp7ai-svc/overlays/development
    repoURL: https://github.com/org4rong/py3ocp7ai-src-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-development
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: "*"
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name | contains("-dockercfg-"))'
      kind: ServiceAccount
    - group: kubeflow.org
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "oauth-proxy")'
        - '.spec.template.spec.volumes[] | select(.name | IN("trusted-ca", "oauth-config", "tls-certificates"))'
        - '.spec.template.spec.containers[] | select(.name != "oauth-proxy").env[] | select(.name | IN("PIP_CERT", "REQUESTS_CA_BUNDLE", "SSL_CERT_FILE", "PIPELINES_SSL_SA_CERTS", "GIT_SSL_CAINFO"))'
        - '.spec.template.spec.containers[] | select(.name != "oauth-proxy").volumeMounts[] | select(.name == "trusted-ca")'
      kind: Notebook
    - group: route.openshift.io
      jsonPointers:
        - /metadata/annotations/openshift.io~1host.generated
        - /spec/alternateBackends
      kind: Route
    - group: batch
      jsonPointers:
        - /spec/selector
        - /spec/completionMode
      kind: Job
    # Ignore StatefulSet volumeClaimTemplates (ArgoCD adds apiVersion/kind)
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
    # Ignore InferenceService Stopped condition (causes false "Progressing" status when False)
    - group: serving.kserve.io
      kind: InferenceService
      jqPathExpressions:
        - '.status.conditions[] | select(.type == "Stopped" and .status == "False")'
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
