apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Using token auth for cluster-wide access
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets-system"
          key: "token"
