apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-hftoken
  namespace: tssc-app-development
spec:
  refreshInterval: "0" # Never refresh (infinite)
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-huggingface-secret
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: rag
        property: hf_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-stack-env-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-llama-stack-env
  data:
    - secretKey: TAVILY_SEARCH_API_KEY
      remoteRef:
        key: rag
        property: TAVILY_SEARCH_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tavily-secret-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-tavily-secret
  data:
    - secretKey: TAVILY_API_KEY
      remoteRef:
        key: rag
        property: TAVILY_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgvector-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-pgvector
  data:
    - secretKey: user
      remoteRef:
        key: rag/pgvector
        property: user
    - secretKey: password
      remoteRef:
        key: rag/pgvector
        property: password
    - secretKey: host
      remoteRef:
        key: rag/pgvector
        property: host
    - secretKey: port
      remoteRef:
        key: rag/pgvector
        property: port
    - secretKey: dbname
      remoteRef:
        key: rag/pgvector
        property: dbname
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-minio
  data:
    - secretKey: user
      remoteRef:
        key: rag/minio
        property: user
    - secretKey: password
      remoteRef:
        key: rag/minio
        property: password
    - secretKey: host
      remoteRef:
        key: rag/minio
        property: host
    - secretKey: port
      remoteRef:
        key: rag/minio
        property: port
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipeline-secrets-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-pipeline-secrets
  data:
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: rag/pipeline
        property: MINIO_ENDPOINT
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: rag/pipeline
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: rag/pipeline
        property: MINIO_SECRET_KEY
    - secretKey: LLAMASTACK_BASE_URL
      remoteRef:
        key: rag/pipeline
        property: LLAMASTACK_BASE_URL
    - secretKey: DS_PIPELINE_URL
      remoteRef:
        key: rag/pipeline
        property: DS_PIPELINE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingestion-pipeline-from-vault
  namespace: tssc-app-development
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-ingestion-pipeline-secret
  data:
    - secretKey: SOURCE
      remoteRef:
        key: rag/ingestion
        property: SOURCE
    - secretKey: EMBEDDING_MODEL
      remoteRef:
        key: rag/ingestion
        property: EMBEDDING_MODEL
    - secretKey: NAME
      remoteRef:
        key: rag/ingestion
        property: NAME
    - secretKey: VERSION
      remoteRef:
        key: rag/ingestion
        property: VERSION
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: rag/ingestion
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: rag/ingestion
        property: SECRET_ACCESS_KEY
    - secretKey: ENDPOINT_URL
      remoteRef:
        key: rag/ingestion
        property: ENDPOINT_URL
    - secretKey: BUCKET_NAME
      remoteRef:
        key: rag/ingestion
        property: BUCKET_NAME
    - secretKey: REGION
      remoteRef:
        key: rag/ingestion
        property: REGION
