apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-data
  labels:
    app.kubernetes.io/name: weather
    app.kubernetes.io/instance: rag
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

