# Source: rag/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/name: rag
    app.kubernetes.io/instance: rag
    app.kubernetes.io/version: "0.2.14"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: py3ocp7ai-svc-gitops
  name: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rag
      app.kubernetes.io/instance: rag
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rag
        app.kubernetes.io/instance: rag
        app.kubernetes.io/version: "0.2.14"
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: default
      securityContext: null
      containers:
        - name: rag
          securityContext: null
          image: "quay.io/ecosystem-appeng/llamastack-dist-ui:0.2.9"
          imagePullPolicy: IfNotPresent
          env:
            - name: LLAMA_STACK_ENDPOINT
              value: http://llamastack:8321
            - name: TMPDIR
              value: /tmp
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: null
          volumeMounts:
            - mountPath: /.streamlit
              name: dot-streamlit
      volumes:
        - emptyDir: {}
          name: dot-streamlit
