# Source: rag/charts/mcp-servers/charts/toolhive-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/name: toolhive-operator
    app.kubernetes.io/instance: rag
    app.kubernetes.io/part-of: py3ocp7ai-svc-gitops
    app.kubernetes.io/version: "0.3.5"
    app.kubernetes.io/managed-by: kustomize
  name: toolhive-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toolhive-operator
      app.kubernetes.io/instance: rag
      app.kubernetes.io/part-of: toolhive-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toolhive-operator
        app.kubernetes.io/instance: rag
        app.kubernetes.io/part-of: toolhive-operator
        app.kubernetes.io/version: "0.3.5"
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: toolhive-operator
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/stacklok/toolhive/operator:v0.3.5"
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          env:
            # Always use structured JSON logs in Kubernetes (not configurable)
            - name: UNSTRUCTURED_LOGS
              value: "false"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENABLE_EXPERIMENTAL_FEATURES
              value: "false"
            - name: TOOLHIVE_RUNNER_IMAGE
              value: "ghcr.io/stacklok/toolhive/proxyrunner:v0.3.5"
            - name: TOOLHIVE_PROXY_HOST
              value: "0.0.0.0"
            - name: TOOLHIVE_REGISTRY_API_IMAGE
              value: "ghcr.io/stacklok/toolhive/thv-registry-api:latest"
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
