# Source: rag/charts/minio/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rag-minio
  labels:
    app.kubernetes.io/name: rag-minio
    app.kubernetes.io/instance: rag
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rag-minio
      app.kubernetes.io/instance: rag
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rag-minio
        app.kubernetes.io/instance: rag
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: default
      containers:
        - name: rag-minio
          image: "quay.io/minio/minio:latest"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: rag-minio
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rag-minio
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-data
