# Source: rag/charts/configure-pipeline/templates/notebook.yaml
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: rag-pipeline-notebook
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: Standard Data Science
    notebooks.opendatahub.io/oauth-logout-url: ""
    openshift.io/display-name: rag-pipeline-notebook
spec:
  template:
    spec:
      serviceAccountName: rag-pipeline-notebook
      initContainers:
        - name: clone-notebook-repo
          image: alpine/git
          command:
            - /bin/sh
            - -c
            - |
              echo "Cleaning /opt/app-root/src..." && \
              rm -rf /opt/app-root/src/* && \
              echo "Cloning repo..." && \
              git clone https://github.com/RHEcosystemAppEng/RAG-Blueprint.git /tmp/notebook && \
              cp -r /tmp/notebook/notebooks/* /opt/app-root/src && \
              rm -rf /tmp/notebook
          volumeMounts:
            - name: pipeline-vol
              mountPath: /opt/app-root/src
      containers:
        - name: rag-pipeline-notebook
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rag-pipeline-secrets
                  key: MINIO_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-pipeline-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-pipeline-secrets
                  key: MINIO_SECRET_KEY
            - name: LLAMASTACK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: rag-pipeline-secrets
                  key: LLAMASTACK_BASE_URL
            - name: DS_PIPELINE_URL
              valueFrom:
                secretKeyRef:
                  name: rag-pipeline-secrets
                  key: DS_PIPELINE_URL
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/tssc-app-development/rag-pipeline-notebook
                --ServerApp.quit_button=False
                --ServerApp.tornado_settings={"user":"user1","hub_host":"","hub_prefix":"/projects/"}
            - name: JUPYTER_IMAGE
              value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2
          imagePullPolicy: Always
          volumeMounts:
            - name: pipeline-vol
              mountPath: /opt/app-root/src
            - name: shm
              mountPath: /dev/shm
      enableServiceLinks: false
      volumes:
        - name: pipeline-vol
          persistentVolumeClaim:
            claimName: pipeline-vol
        - emptyDir:
            medium: Memory
          name: shm
