# Source: rag/charts/mcp-servers/charts/toolhive-operator/templates/clusterrole/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toolhive-operator-manager-rolebinding
  labels:
    app: toolhive
    app.kubernetes.io/name: toolhive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: toolhive-operator-manager-role
subjects:
- kind: ServiceAccount
  name: toolhive-operator
  # namespace: tssc-app-development  # Managed by Kustomize overlay
