# Source: rag/charts/llama-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: llamastack
  labels:
    app.kubernetes.io/name: llamastack
    app.kubernetes.io/instance: rag
    app.kubernetes.io/version: "0.2.18"
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 8321
      targetPort: 8321
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: llamastack
    app.kubernetes.io/instance: rag
